### ISSUE TITLE
disable sidebar

### ISSUE THREAD

**Issue by codingedgar** [tzuehlke/jekyll-uno-timeline#1]
Love this theme!

Is any simple way to disable the sidebar (`#projects`)?

**Comment by tzuehlke** [comment]
You can hide the [project button](https://github.com/tzuehlke/jekyll-uno-timeline/blob/1ced42ffd029a7b178a1ecaff6dd9db6abf567e0/_includes/header.html#L97) or disable the the [toggle lines](https://github.com/tzuehlke/jekyll-uno-timeline/blob/1ced42ffd029a7b178a1ecaff6dd9db6abf567e0/js/main.js#L45-L46) should do the trick (untested).
