### ISSUE TITLE
[Suggestion] Add a CV in the same style the projects "page"

### ISSUE THREAD

**Issue by gleitoncampos** [tzuehlke/jekyll-uno-timeline#5]
Hi Mr. Zühlke, thank you very much for you work in this theme. 
Is possible to take some type of cv and add it in the page to achieve the same slide style the projetcts section do?

For example, add the https://github.com/sharu725/online-cv into the workspace and put in the same page, with the slide effect?

Thank you again!

**Comment by tzuehlke** [comment]
@gleitoncampos this theme uses the https://github.com/le4ker/personal-jekyll-theme?tab=readme-ov-file for showing project. But the original idea is to show a little CV. so feel free to reuse it or write some CV stuff instead of projects.
