### ISSUE TITLE
The icons don't show up successfully

### ISSUE THREAD

**Issue by GiveMeAnApple99** [tzuehlke/jekyll-uno-timeline#7]
After I ran this project, and opened it at `http://localhost:4000`
I found that the icons didn't show up successfully like this ↓
![image](https://user-images.githubusercontent.com/55051102/226577924-45e72a7e-6f8b-4527-92b0-c85c7495bb2b.png)
which was different from your demo
![image](https://user-images.githubusercontent.com/55051102/226579065-92eb482e-70d2-4129-879a-1227f354feea.png)
Could you help me to solve this problem？Thank u.

**Comment by andrej-zirko** [comment]
Register here
https://fontawesome.com/

then enter the id in the _config.yml
font_awesome: 'ID_HERE.js'

**Comment by DiogoVBol** [comment]
hey, i'm having the same problem. I already created my acc in fontawesome, but i can't find ID. What's is this id? It seems to be something simple but I've never used Font Awesome

**Comment by andrej-zirko** [comment]
Go to your kits, under your account. The ID of your kit, is the id you are
looking for

**Comment by tzuehlke** [comment]
@GiveMeAnApple99 see @andrej-zirko answers :-)
